from datetime import UTC, datetime  # Import timezone-aware datetime utilities
from unittest.mock import MagicMock  # Import configurable test doubles
from uuid import UUID, uuid4  # Import UUID typing and generation

import pytest  # Import pytest exception assertions
from sqlalchemy.orm import (
    Session,
)  # Import the Session type used as a mock specification

from app.models import Job  # Import the ORM entity manipulated by the service
from app.repositories import (
    DuplicateJobError,
    JobRepository,
)  # Import repository contracts
from app.schemas import JobCreate, JobUpdate  # Import validated service input schemas
from app.services import (  # Import the service and business exceptions under test
    JobAlreadyExistsError,
    JobNotFoundError,
    JobService,
)


def _build_job_create(
    *,
    external_id: str = "unit-job-123",
    title: str = "Unit Test AI Engineer",
    url: str = "https://example.com/jobs/unit-job-123",
) -> JobCreate:
    """Build one valid JobCreate schema for isolated service tests."""

    return JobCreate.model_validate(
        {
            "source": "unit_test",
            "external_id": external_id,
            "title": title,
            "company_name": "Swiss Unit Bank",
            "location": "Geneva, Switzerland",
            "description": "Validate isolated Job Service business behavior.",
            "employment_type": "full_time",
            "seniority_level": "senior",
            "workplace_type": "hybrid",
            "url": url,
            "posted_at": "2026-07-24T09:00:00+02:00",
        }
    )


def _build_persisted_job(
    *,
    job_id: UUID | None = None,
    external_id: str = "persisted-unit-job",
    title: str = "Persisted AI Engineer",
    url: str = "https://example.com/jobs/persisted-unit-job",
) -> Job:
    """Build one ORM Job populated like a record returned by PostgreSQL."""

    current_time = datetime.now(UTC)

    return Job(
        id=job_id or uuid4(),
        source="unit_test",
        external_id=external_id,
        title=title,
        company_name="Swiss Unit Bank",
        location="Zurich, Switzerland",
        description="Represent a persisted Job during isolated service tests.",
        employment_type="full_time",
        seniority_level="senior",
        workplace_type="hybrid",
        url=url,
        posted_at=current_time,
        discovered_at=current_time,
        is_active=True,
        created_at=current_time,
        updated_at=current_time,
    )


def _build_service() -> tuple[JobService, MagicMock, MagicMock]:
    """Build a JobService with mocked transaction and repository dependencies."""

    session = MagicMock(spec=Session)
    repository = MagicMock(spec=JobRepository)

    service = JobService(
        session=session,
        repository=repository,
    )

    return service, session, repository


def test_service_create_coordinates_repository_and_commit() -> None:
    """Verify successful creation, commit, refresh, and response conversion."""

    service, session, repository = _build_service()
    job_data = _build_job_create()

    def persist_job(job: Job) -> Job:
        """Simulate values normally generated by SQLAlchemy and PostgreSQL."""

        current_time = datetime.now(UTC)

        job.id = uuid4()
        job.discovered_at = current_time
        job.is_active = True
        job.created_at = current_time
        job.updated_at = current_time

        return job

    repository.create.side_effect = persist_job

    response = service.create_job(job_data)

    repository.create.assert_called_once()
    created_entity = repository.create.call_args.args[0]

    assert isinstance(created_entity, Job)
    assert created_entity.title == job_data.title
    assert created_entity.url == str(job_data.url)

    session.commit.assert_called_once_with()
    session.refresh.assert_called_once_with(created_entity)
    session.rollback.assert_not_called()

    assert response.id == created_entity.id
    assert response.title == job_data.title


def test_service_create_rolls_back_and_translates_duplicate() -> None:
    """Verify duplicate persistence failures become business exceptions."""

    service, session, repository = _build_service()

    repository.create.side_effect = DuplicateJobError(constraint_name="uq_jobs_url")

    with pytest.raises(JobAlreadyExistsError) as error_info:
        service.create_job(_build_job_create())

    assert error_info.value.constraint_name == "uq_jobs_url"
    assert str(error_info.value) == "A job with the same URL already exists."

    session.rollback.assert_called_once_with()
    session.commit.assert_not_called()
    session.refresh.assert_not_called()


def test_service_create_rolls_back_unexpected_error() -> None:
    """Verify unexpected creation failures are rolled back and preserved."""

    service, session, repository = _build_service()
    technical_error = RuntimeError("Unexpected persistence failure")

    repository.create.side_effect = technical_error

    with pytest.raises(RuntimeError, match="Unexpected persistence failure"):
        service.create_job(_build_job_create())

    session.rollback.assert_called_once_with()
    session.commit.assert_not_called()


def test_service_get_missing_job_raises_without_transaction_change() -> None:
    """Verify read-only absence handling does not commit or roll back."""

    service, session, repository = _build_service()
    missing_id = uuid4()

    repository.get_by_id.return_value = None

    with pytest.raises(JobNotFoundError) as error_info:
        service.get_job(missing_id)

    repository.get_by_id.assert_called_once_with(missing_id)
    assert error_info.value.job_id == missing_id

    session.commit.assert_not_called()
    session.rollback.assert_not_called()


def test_service_list_delegates_pagination_and_builds_response() -> None:
    """Verify pagination calls and public collection construction."""

    service, session, repository = _build_service()

    jobs = [
        _build_persisted_job(
            external_id=f"unit-list-{index}",
            title=f"Unit AI Engineer {index}",
            url=f"https://example.com/jobs/unit-list-{index}",
        )
        for index in range(2)
    ]

    repository.list.return_value = jobs
    repository.count.return_value = 7

    page = service.list_jobs(
        offset=2,
        limit=2,
    )

    repository.list.assert_called_once_with(
        offset=2,
        limit=2,
    )
    repository.count.assert_called_once_with()

    assert len(page.items) == 2
    assert page.total == 7
    assert page.offset == 2
    assert page.limit == 2

    session.commit.assert_not_called()
    session.rollback.assert_not_called()


def test_service_update_applies_only_provided_fields_and_commits() -> None:
    """Verify partial updates preserve omitted ORM attributes."""

    service, session, repository = _build_service()

    persisted_job = _build_persisted_job(
        title="Original Unit Engineer",
    )
    original_company_name = persisted_job.company_name
    original_location = persisted_job.location

    repository.get_by_id.return_value = persisted_job
    repository.update.return_value = persisted_job

    update_data = JobUpdate.model_validate(
        {
            "title": "Updated Unit Engineer",
            "is_active": False,
        }
    )

    response = service.update_job(
        persisted_job.id,
        update_data,
    )

    repository.get_by_id.assert_called_once_with(persisted_job.id)
    repository.update.assert_called_once_with(persisted_job)

    session.commit.assert_called_once_with()
    session.refresh.assert_called_once_with(persisted_job)
    session.rollback.assert_not_called()

    assert persisted_job.title == "Updated Unit Engineer"
    assert persisted_job.is_active is False
    assert persisted_job.company_name == original_company_name
    assert persisted_job.location == original_location

    assert response.title == "Updated Unit Engineer"
    assert response.is_active is False


def test_service_update_rolls_back_and_translates_duplicate() -> None:
    """Verify duplicate conflicts during updates become business exceptions."""

    service, session, repository = _build_service()

    persisted_job = _build_persisted_job()
    repository.get_by_id.return_value = persisted_job
    repository.update.side_effect = DuplicateJobError(constraint_name="uq_jobs_url")

    update_data = JobUpdate.model_validate(
        {
            "url": "https://example.com/jobs/already-existing",
        }
    )

    with pytest.raises(JobAlreadyExistsError) as error_info:
        service.update_job(
            persisted_job.id,
            update_data,
        )

    assert error_info.value.constraint_name == "uq_jobs_url"

    session.rollback.assert_called_once_with()
    session.commit.assert_not_called()
    session.refresh.assert_not_called()


def test_service_delete_commits_successful_deletion() -> None:
    """Verify deletion delegates to the Repository and commits once."""

    service, session, repository = _build_service()

    persisted_job = _build_persisted_job()
    repository.get_by_id.return_value = persisted_job

    service.delete_job(persisted_job.id)

    repository.get_by_id.assert_called_once_with(persisted_job.id)
    repository.delete.assert_called_once_with(persisted_job)

    session.commit.assert_called_once_with()
    session.rollback.assert_not_called()


def test_service_delete_rolls_back_unexpected_error() -> None:
    """Verify deletion failures are rolled back and re-raised."""

    service, session, repository = _build_service()

    persisted_job = _build_persisted_job()
    repository.get_by_id.return_value = persisted_job
    repository.delete.side_effect = RuntimeError("Delete operation failed")

    with pytest.raises(RuntimeError, match="Delete operation failed"):
        service.delete_job(persisted_job.id)

    session.rollback.assert_called_once_with()
    session.commit.assert_not_called()
