"""create jobs table

Revision ID: 195bfce49ec8
Revises: 88cc65105256
Create Date: 2026-07-22 00:53:44.316553

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "195bfce49ec8"
down_revision: Union[str, Sequence[str], None] = "88cc65105256"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("employment_type", sa.String(length=50), nullable=True),
        sa.Column("seniority_level", sa.String(length=50), nullable=True),
        sa.Column("workplace_type", sa.String(length=50), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "discovered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "employment_type IS NULL OR employment_type IN ('full_time', 'part_time', 'contract', 'temporary', 'internship', 'freelance', 'apprenticeship')",
            name=op.f("ck_jobs_employment_type_allowed"),
        ),
        sa.CheckConstraint(
            "seniority_level IS NULL OR seniority_level IN ('internship', 'entry', 'junior', 'mid', 'senior', 'lead', 'manager', 'director', 'executive')",
            name=op.f("ck_jobs_seniority_level_allowed"),
        ),
        sa.CheckConstraint(
            "workplace_type IS NULL OR workplace_type IN ('onsite', 'hybrid', 'remote')",
            name=op.f("ck_jobs_workplace_type_allowed"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("source", "external_id", name="uq_jobs_source_external_id"),
        sa.UniqueConstraint("url", name=op.f("uq_jobs_url")),
    )
    op.create_index(
        "ix_jobs_active_posted_at", "jobs", ["is_active", "posted_at"], unique=False
    )
    op.create_index("ix_jobs_location", "jobs", ["location"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_jobs_location", table_name="jobs")
    op.drop_index("ix_jobs_active_posted_at", table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###
